### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by edoyango**
Hi @jIskCoder 

I've added a dockerfile to the repo with the container. I used a combination of the environments and nextflow.config modules to get the dependencies.

The container is currently located at `ghcr.io/wehi-researchcomputing/malaria-env:latest` which I've updated the pipeline to use when `-profile singularity` is specified.

Can you give it a try?

### CODE REVIEW

**Comment by jIskCoder** [comment]
@edoyango I get an error when running using singularity 

> ERROR ~ Error executing process > 'Bwa (2)'
> 
> Caused by:
>   Failed to pull singularity image
>   command: singularity pull  --name ghcr.io-wehi-researchcomputing-malaria-env-latest.img.pulling.1709778919018 docker://ghcr.io/wehi-researchcomputing/malaria-env:latest > /dev/null
>   status : 255
>   message:
>     FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://ghcr.io/wehi-researchcomputing/malaria-env:latest: unable to retrieve auth token: invalid username/password: unauthorized
> 
> 
> 
>  -- Check '.nextflow.log' file for details

**Comment by edoyango** [comment]
@jIskCoder The container was internal before, now it should be public. Can you try again?

**Comment by jIskCoder** [comment]
[nextflow.log](https://github.com/WEHI-ResearchComputing/nf-malaria-variant-analysis/files/14518317/nextflow.log)
Still failing to pull image
@edoyango

**Comment by edoyango** [comment]
@jIskCoder I'm not sure why your pull is failing - I can pull the container without issue. Where are you running this? error code 143 means the command was killed. Can you give me test data?

**Comment by jIskCoder** [comment]
I am testing process by process. It seems in the index step the MarkDuplicates is not installed

> MarkDuplicates: command not found

@edoyango

**Comment by edoyango** [comment]
@jIskCoder 
I've pushed a new container which should have a working MarkDuplicates. Can you give it another try?

**Comment by edoyango** [comment]
@jIskCoder I've updated the config to make the timeout 1h instead of 20mins. Can you give it another try?

**Comment by jIskCoder** [comment]
[like]  Julie Iskander reacted to your message:
________________________________

**Comment by edoyango** [comment]
@jIskCoder the reference genomes has been added to the container. Try again?

**Pull request merged**
